server :
  port: 8888
spring:
  cloud:
    config:
      server:
        git:   
          uri: file://Users/whthomas/config-repo
  application:
    name: configserver
  cloud:
    config:
      uri:  http://localhost:8888